### ISSUE TITLE
Use a more flexible config format

### ISSUE THREAD

**Issue by paalbra** [unioslo/zabbix-auto-config#12]
Switch to something more flexible than the INI format for config.

Maybe YAML, JSON or TOML.

**Comment by paalbra** [comment]
YAML *might* be the best choice right now, but I believe it's worth looking into how TOML is received in v1.0 (currently v1.0.0-rc.1):

https://github.com/toml-lang/toml

Zabbix-auto-config itself might not benefit much from switching from ini, but the source collectors could have a simpler config if using other formats.

**Comment by paalbra** [comment]
TOML seems like a good choice, but it's currently not obvious which library to choose. Looks like others might be leaning towards [tomli](https://github.com/hukkin/tomli)

**Comment by mbakke** [comment]
TOML and `tomli` seem like fine options to me.

**Comment by paalbra** [comment]
tomli seems like a good choice. People have been working to propose it as a stdlib module: https://github.com/hukkin/tomli/issues/141
